server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EAP5?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.game.user.entity
  mapper-locations: classpath:mapper/*.xml